/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.frame.views;

import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JOptionPane;
import com.kontrol.classapk.kontrol_laporan;
/**
 *
 * @author HP
 */
public class cetak extends javax.swing.JDialog {
kontrol_laporan kl;
ResultSet rs;
    /**
     * Creates new form cetak
     */
    public cetak(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        kl = new kontrol_laporan();
        txtcetaknik.requestFocus();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcetaknik = new javax.swing.JTextField();
        btncetak = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtcetakid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CETAK LAPORAN NIK");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 72, -1, -1));
        jPanel1.add(txtcetaknik, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 142, 279, -1));

        btncetak.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btncetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/frame/actions_document_print_preview_15786.png"))); // NOI18N
        btncetak.setText("Cetak");
        btncetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncetakMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncetakMouseExited(evt);
            }
        });
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });
        jPanel1.add(btncetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 280, 60));

        jLabel2.setText("Silahkan input NIK anda");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 122, -1, -1));
        jPanel1.add(txtcetakid, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 180, 279, -1));

        jLabel3.setText("Silahkan input ID PENGADUAN anda");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 163, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        // TODO add your handling code here:
        if (txtcetaknik.getText().isEmpty() ||
            txtcetakid.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Silahkan input ID Transaksi dahulu","Informasi",JOptionPane.WARNING_MESSAGE);
            txtcetaknik.requestFocus();
        } else {
        dispose();
        String lokasi = "src/com/data/ireport/reportmasyarakat.jrxml";
        HashMap map = new HashMap();
        map.put("nik",txtcetaknik.getText());
        map.put("id_pengaduan",txtcetakid.getText());
        kl.cetaklaporannik(lokasi, map);
        }
    }//GEN-LAST:event_btncetakActionPerformed

    private void btncetakMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncetakMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btncetakMouseEntered

    private void btncetakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncetakMouseExited
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btncetakMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cetak dialog = new cetak(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcetakid;
    private javax.swing.JTextField txtcetaknik;
    // End of variables declaration//GEN-END:variables

}
