/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frame.views;

import javax.swing.ImageIcon;

/**
 *
 * @author HP
 */
public class menupetugas extends javax.swing.JFrame {
    /**
     * Creates new form menupetugas
     */
    public menupetugas() {
        initComponents();
       
    }
   
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        penjelas_masker = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblusername = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblidpetugas = new javax.swing.JLabel();
        lblhakakses = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_menjaga_jarak = new javax.swing.JLabel();
        btn_mencuci_tangan = new javax.swing.JLabel();
        btn_memakai_masker = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        data_tanggapan = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        verifikasi = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        laporan_tanggapan = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        penjelas_masker.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        penjelas_masker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/background/frame/penjelas_btn_memakai_masker.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Hallo");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 80, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 90, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblusername.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblusername.setForeground(new java.awt.Color(102, 102, 255));
        lblusername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblusername.setText("lblusername");
        jPanel1.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 100, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 110, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblidpetugas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblidpetugas.setForeground(new java.awt.Color(102, 102, 255));
        lblidpetugas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblidpetugas.setText("lblidpetugas");
        jPanel3.add(lblidpetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 110, 20));

        lblhakakses.setForeground(new java.awt.Color(255, 255, 255));
        lblhakakses.setText("lblhakakses");
        getContentPane().add(lblhakakses, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 80, -1));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Anda Sebagai :");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 90, -1));

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Aplikasi Pelaporan Pengaduan Masyarakat");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel6.setText("-------------------");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, -1, -1));

        jLabel5.setText("-------------------");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, -1, -1));

        btn_menjaga_jarak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_menjaga_jarak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/background/frame/btn_menjaga_jarak.png"))); // NOI18N
        btn_menjaga_jarak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_menjaga_jarakMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menjaga_jarakMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menjaga_jarakMouseExited(evt);
            }
        });
        getContentPane().add(btn_menjaga_jarak, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 170, 210));

        btn_mencuci_tangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_mencuci_tangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/background/frame/btn_mencuci_tangan.png"))); // NOI18N
        btn_mencuci_tangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mencuci_tanganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mencuci_tanganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mencuci_tanganMouseExited(evt);
            }
        });
        getContentPane().add(btn_mencuci_tangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 170, 210));

        btn_memakai_masker.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_memakai_masker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/background/frame/btn_memakai_masker.png"))); // NOI18N
        btn_memakai_masker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_memakai_maskerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_memakai_maskerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_memakai_maskerMouseExited(evt);
            }
        });
        getContentPane().add(btn_memakai_masker, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 170, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/background/frame/menu_utama.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 580));

        jMenu1.setText("Input Data Master");

        data_tanggapan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        data_tanggapan.setText("Input Data Tanggapan");
        data_tanggapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_tanggapanActionPerformed(evt);
            }
        });
        jMenu1.add(data_tanggapan);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Verifikasi");

        verifikasi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        verifikasi.setText("Verifikasi Pengaduan(petugas)");
        verifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifikasiActionPerformed(evt);
            }
        });
        jMenu2.add(verifikasi);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Detail Data");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Detail Data Tanggapan Lengkap");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        laporan_tanggapan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        laporan_tanggapan.setText("Detail Data Tanggapan");
        laporan_tanggapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_tanggapanActionPerformed(evt);
            }
        });
        jMenu5.add(laporan_tanggapan);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Pengaturan");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Developer");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.CTRL_MASK));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu4.add(logout);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_memakai_maskerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_memakai_maskerMouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/com/background/frame/trans_btn_memakai_masker.png"));
        btn_memakai_masker.setIcon(II);
    }//GEN-LAST:event_btn_memakai_maskerMouseEntered

    private void btn_memakai_maskerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_memakai_maskerMouseClicked
        // TODO add your handling code here:
        info_masker m1 = new info_masker(this, true);
        m1.setVisible(true);
    }//GEN-LAST:event_btn_memakai_maskerMouseClicked

    private void btn_mencuci_tanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mencuci_tanganMouseClicked
        // TODO add your handling code here:
        info_mencucitngn m2 = new info_mencucitngn(this, true);
        m2.setVisible(true);
    }//GEN-LAST:event_btn_mencuci_tanganMouseClicked

    private void btn_mencuci_tanganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mencuci_tanganMouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/com/background/frame/trans_btn_mencuci_tangan.png"));
        btn_mencuci_tangan.setIcon(II);
    }//GEN-LAST:event_btn_mencuci_tanganMouseEntered

    private void btn_memakai_maskerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_memakai_maskerMouseExited
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/com/background/frame/btn_memakai_masker.png"));
        btn_memakai_masker.setIcon(II);
    }//GEN-LAST:event_btn_memakai_maskerMouseExited

    private void btn_mencuci_tanganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mencuci_tanganMouseExited
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/com/background/frame/btn_mencuci_tangan.png"));
        btn_mencuci_tangan.setIcon(II);
    }//GEN-LAST:event_btn_mencuci_tanganMouseExited

    private void btn_menjaga_jarakMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menjaga_jarakMouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/com/background/frame/trans_btn_menjaga_jarak.png"));
        btn_menjaga_jarak.setIcon(II);
    }//GEN-LAST:event_btn_menjaga_jarakMouseEntered

    private void btn_menjaga_jarakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menjaga_jarakMouseExited
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/com/background/frame/btn_menjaga_jarak.png"));
        btn_menjaga_jarak.setIcon(II);
    }//GEN-LAST:event_btn_menjaga_jarakMouseExited

    private void btn_menjaga_jarakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menjaga_jarakMouseClicked
        // TODO add your handling code here:
         info_menjagajrk m3 = new info_menjagajrk(this, true);
         m3.setVisible(true);
    }//GEN-LAST:event_btn_menjaga_jarakMouseClicked

    private void data_tanggapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_tanggapanActionPerformed
        // TODO add your handling code here:
        tanggapan t = new tanggapan(this, true);
        t.txtidpetugas.setText(lblidpetugas.getText());
        t.setVisible(true);
    }//GEN-LAST:event_data_tanggapanActionPerformed

    private void verifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifikasiActionPerformed
        // TODO add your handling code here:
        verifikasipengaduan v = new verifikasipengaduan(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_verifikasiActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
       dispose();
       loginpetugas l = new loginpetugas();
       l.setVisible(true);
      
    }//GEN-LAST:event_logoutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
       info_tentangku it = new info_tentangku(this, true);
       it.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void laporan_tanggapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_tanggapanActionPerformed
        // TODO add your handling code here:
         detaildatatanggapan a = new detaildatatanggapan(this, true);
         a.setVisible(true);
    }//GEN-LAST:event_laporan_tanggapanActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        detail_all_data dad = new detail_all_data(this, true);
        dad.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menupetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menupetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menupetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menupetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menupetugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_memakai_masker;
    private javax.swing.JLabel btn_mencuci_tangan;
    private javax.swing.JLabel btn_menjaga_jarak;
    public javax.swing.JMenuItem data_tanggapan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JMenuItem laporan_tanggapan;
    public javax.swing.JLabel lblhakakses;
    public javax.swing.JLabel lblidpetugas;
    public javax.swing.JLabel lblusername;
    public javax.swing.JMenuItem logout;
    private javax.swing.JLabel penjelas_masker;
    public javax.swing.JMenuItem verifikasi;
    // End of variables declaration//GEN-END:variables

   
}
