/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frame.views;

import com.kontrol.classapk.kontrol_petugas;
import javax.swing.ImageIcon;
import com.kontrol.classapk.koneksi;
import com.kontrol.classapk.kontrol_laporan;
import java.util.HashMap;

/**
 *
 * @author HP
 */
public class menuadmin extends javax.swing.JFrame {
     kontrol_petugas p;
     kontrol_laporan kl;
     koneksi konek = new koneksi();
    /**
     * Creates new form menuadmin
     */
    
    
     
    public menuadmin() {
        initComponents();
        p = new kontrol_petugas();
        kl = new kontrol_laporan();
         konek.setkonek();
        penjelas();
        
       
    }
   
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblidadmin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblusername = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblhakakses = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_menjaga_jarak = new javax.swing.JLabel();
        btn_mencuci_tangan = new javax.swing.JLabel();
        btn_memakai_masker = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        data_privilege = new javax.swing.JMenuItem();
        data_masyarakat = new javax.swing.JMenuItem();
        data_tanggapan = new javax.swing.JMenuItem();
        cetak_laporan_nik = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        verifikasi = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        laporan_masyarakat = new javax.swing.JMenuItem();
        laporan_pengaduan = new javax.swing.JMenuItem();
        laporan_tanggapan = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Hallo");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 80, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 90, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblidadmin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblidadmin.setForeground(new java.awt.Color(102, 102, 255));
        lblidadmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblidadmin.setText("lblidadmin");
        jPanel3.add(lblidadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 110, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblusername.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblusername.setForeground(new java.awt.Color(102, 102, 255));
        lblusername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblusername.setText("lblusername");
        jPanel1.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 100, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 110, 20));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("-----------");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 336, -1, 10));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("-----------");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/frame/business_table_order_report_history_2332.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
        });
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 70, 70));

        jLabel21.setFont(new java.awt.Font("Lucida Console", 0, 8)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Generate Laporan");
        jLabel21.setToolTipText("");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 90, 10));

        lblhakakses.setForeground(new java.awt.Color(255, 255, 255));
        lblhakakses.setText("lblhakakses");
        getContentPane().add(lblhakakses, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 80, -1));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Anda Sebagai :");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 90, -1));

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Aplikasi Pelaporan Pengaduan Masyarakat");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel20.setFont(new java.awt.Font("Lucida Console", 0, 8)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Tanggapan");
        jLabel20.setToolTipText("");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 10));

        jLabel18.setFont(new java.awt.Font("Lucida Console", 0, 8)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Masyarakat");
        jLabel18.setToolTipText("");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 10));

        jLabel17.setFont(new java.awt.Font("Lucida Console", 0, 8)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Privilege");
        jLabel17.setToolTipText("");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 60, 10));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("-----------");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 20));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("-----------");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/frame/userreviews_usuario_12980_1.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 70));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("-----------");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/frame/User (1).png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, 70));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("-----------");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("-----------");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/frame/user.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 60, 60));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("-----------");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("-----------");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel6.setText("-------------------");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, -1, -1));

        jLabel5.setText("-------------------");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, -1, -1));

        btn_menjaga_jarak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_menjaga_jarak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/background/frame/btn_menjaga_jarak.png"))); // NOI18N
        btn_menjaga_jarak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_menjaga_jarakMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menjaga_jarakMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menjaga_jarakMouseExited(evt);
            }
        });
        getContentPane().add(btn_menjaga_jarak, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 170, 210));

        btn_mencuci_tangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_mencuci_tangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/background/frame/btn_mencuci_tangan.png"))); // NOI18N
        btn_mencuci_tangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mencuci_tanganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mencuci_tanganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mencuci_tanganMouseExited(evt);
            }
        });
        getContentPane().add(btn_mencuci_tangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 170, 210));

        btn_memakai_masker.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_memakai_masker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/background/frame/btn_memakai_masker.png"))); // NOI18N
        btn_memakai_masker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_memakai_maskerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_memakai_maskerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_memakai_maskerMouseExited(evt);
            }
        });
        getContentPane().add(btn_memakai_masker, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 170, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/background/frame/menu_utama.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 580));

        jMenu1.setText("Data Master");

        data_privilege.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        data_privilege.setText("Data Privilege");
        data_privilege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_privilegeActionPerformed(evt);
            }
        });
        jMenu1.add(data_privilege);

        data_masyarakat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        data_masyarakat.setText("Data Masyarakat");
        data_masyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_masyarakatActionPerformed(evt);
            }
        });
        jMenu1.add(data_masyarakat);

        data_tanggapan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_MASK));
        data_tanggapan.setText("Data Tanggapan");
        data_tanggapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_tanggapanActionPerformed(evt);
            }
        });
        jMenu1.add(data_tanggapan);

        jMenuBar1.add(jMenu1);

        cetak_laporan_nik.setText("Laporan");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Cetak Laporan NIK");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        cetak_laporan_nik.add(jMenuItem4);

        jMenuBar1.add(cetak_laporan_nik);

        jMenu2.setText("Verifikasi");

        verifikasi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_MASK));
        verifikasi.setText("Verifikasi Pengaduan(petugas)");
        verifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifikasiActionPerformed(evt);
            }
        });
        jMenu2.add(verifikasi);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Detail Data");

        laporan_masyarakat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.CTRL_MASK));
        laporan_masyarakat.setText("Detail Data Masyarakat");
        laporan_masyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_masyarakatActionPerformed(evt);
            }
        });
        jMenu3.add(laporan_masyarakat);

        laporan_pengaduan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.CTRL_MASK));
        laporan_pengaduan.setText("Detail Data Pengaduan");
        laporan_pengaduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_pengaduanActionPerformed(evt);
            }
        });
        jMenu3.add(laporan_pengaduan);

        laporan_tanggapan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, java.awt.event.InputEvent.CTRL_MASK));
        laporan_tanggapan.setText("Detail Data Tanggapan");
        laporan_tanggapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_tanggapanActionPerformed(evt);
            }
        });
        jMenu3.add(laporan_tanggapan);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Detail Data Tanggapan Lengkap");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Pengaturan");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Developer");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, java.awt.event.InputEvent.CTRL_MASK));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu4.add(logout);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_memakai_maskerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_memakai_maskerMouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/com/background/frame/trans_btn_memakai_masker.png"));
        btn_memakai_masker.setIcon(II);
    }//GEN-LAST:event_btn_memakai_maskerMouseEntered

    private void btn_memakai_maskerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_memakai_maskerMouseClicked
        // TODO add your handling code here:
        info_masker m1 = new info_masker(this, true);
        m1.setVisible(true);
    }//GEN-LAST:event_btn_memakai_maskerMouseClicked

    private void btn_mencuci_tanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mencuci_tanganMouseClicked
        // TODO add your handling code here:
        info_mencucitngn m2 = new info_mencucitngn(this, true);
        m2.setVisible(true);
    }//GEN-LAST:event_btn_mencuci_tanganMouseClicked

    private void btn_mencuci_tanganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mencuci_tanganMouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/com/background/frame/trans_btn_mencuci_tangan.png"));
        btn_mencuci_tangan.setIcon(II);
    }//GEN-LAST:event_btn_mencuci_tanganMouseEntered

    private void btn_memakai_maskerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_memakai_maskerMouseExited
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/com/background/frame/btn_memakai_masker.png"));
        btn_memakai_masker.setIcon(II);
    }//GEN-LAST:event_btn_memakai_maskerMouseExited

    private void btn_mencuci_tanganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mencuci_tanganMouseExited
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/com/background/frame/btn_mencuci_tangan.png"));
        btn_mencuci_tangan.setIcon(II);
    }//GEN-LAST:event_btn_mencuci_tanganMouseExited

    private void btn_menjaga_jarakMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menjaga_jarakMouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/com/background/frame/trans_btn_menjaga_jarak.png"));
        btn_menjaga_jarak.setIcon(II);
    }//GEN-LAST:event_btn_menjaga_jarakMouseEntered

    private void btn_menjaga_jarakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menjaga_jarakMouseExited
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/com/background/frame/btn_menjaga_jarak.png"));
        btn_menjaga_jarak.setIcon(II);
    }//GEN-LAST:event_btn_menjaga_jarakMouseExited

    private void btn_menjaga_jarakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menjaga_jarakMouseClicked
        // TODO add your handling code here:
         info_menjagajrk m3 = new info_menjagajrk(this, true);
         m3.setVisible(true);
    }//GEN-LAST:event_btn_menjaga_jarakMouseClicked

    private void data_privilegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_privilegeActionPerformed
        // TODO add your handling code here:
        privilage p = new privilage(this, true);
        p.setVisible(true);
    }//GEN-LAST:event_data_privilegeActionPerformed

    private void data_tanggapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_tanggapanActionPerformed
        // TODO add your handling code here:
      tanggapan t = new tanggapan(this, true);
      t.txtidpetugas.setText(lblidadmin.getText());
      t.setVisible(true);
    }//GEN-LAST:event_data_tanggapanActionPerformed

    private void laporan_pengaduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_pengaduanActionPerformed
        // TODO add your handling code here:
        detaildatapengaduan a = new detaildatapengaduan(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_laporan_pengaduanActionPerformed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        jLabel17.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        jLabel17.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        jLabel18.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        jLabel18.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        // TODO add your handling code here:
        jLabel20.setVisible(true);
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        // TODO add your handling code here:
        jLabel20.setVisible(false);
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        privilage p = new privilage(this, true);
        p.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        tanggapan t = new tanggapan(this, true);
        t.setVisible(true);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void laporan_masyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_masyarakatActionPerformed
        // TODO add your handling code here:
        detaildatamasyarakat m = new detaildatamasyarakat(this, true);
        m.setVisible(true);
    }//GEN-LAST:event_laporan_masyarakatActionPerformed

    private void data_masyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_masyarakatActionPerformed
        // TODO add your handling code here:
        registrasi r = new registrasi(this, true);
        r.setVisible(true);
    }//GEN-LAST:event_data_masyarakatActionPerformed

    private void verifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifikasiActionPerformed
        // TODO add your handling code here:
        verifikasipengaduan v = new verifikasipengaduan(this, true);
        v.setVisible(true);
    }//GEN-LAST:event_verifikasiActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        registrasi r = new registrasi(this, true);
        r.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void laporan_tanggapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_tanggapanActionPerformed
        // TODO add your handling code here:
        detaildatatanggapan n = new detaildatatanggapan(this, true);
        n.setVisible(true);
    }//GEN-LAST:event_laporan_tanggapanActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        String lokasi = "src/com/data/ireport/laporanlngkap.jrxml";
        HashMap map = new HashMap();
        kl.cetaklaporan(lokasi);
        
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
        // TODO add your handling code here:
       jLabel21.setVisible(true);
    }//GEN-LAST:event_jLabel19MouseEntered

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
        // TODO add your handling code here:
       jLabel21.setVisible(false);
    }//GEN-LAST:event_jLabel19MouseExited

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
       cetak c = new cetak(this, true);
       c.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        dispose();
        loginpetugas l = new loginpetugas();
        l.setVisible(true);

    }//GEN-LAST:event_logoutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        info_tentangku it = new info_tentangku(this, true);
        it.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        detail_all_data da = new detail_all_data(this, true);
        da.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_memakai_masker;
    private javax.swing.JLabel btn_mencuci_tangan;
    private javax.swing.JLabel btn_menjaga_jarak;
    private javax.swing.JMenu cetak_laporan_nik;
    public javax.swing.JMenuItem data_masyarakat;
    public javax.swing.JMenuItem data_privilege;
    public javax.swing.JMenuItem data_tanggapan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JMenuItem laporan_masyarakat;
    public javax.swing.JMenuItem laporan_pengaduan;
    public javax.swing.JMenuItem laporan_tanggapan;
    public javax.swing.JLabel lblhakakses;
    public javax.swing.JLabel lblidadmin;
    public javax.swing.JLabel lblusername;
    public javax.swing.JMenuItem logout;
    public javax.swing.JMenuItem verifikasi;
    // End of variables declaration//GEN-END:variables

    private void penjelas() {
    jLabel17.setVisible(false);
    jLabel18.setVisible(false);
    jLabel20.setVisible(false);
    jLabel21.setVisible(false);
}
}
